baseurl:  ""
markdown: redcarpet
highlighter: true
exclude: [Rakefile, README.md]

# Site settings
title:        "Free's blog"
description:  "Free's personal blog"
techcategories: [Ruby, Rails, Database, Linux, Designs, Javascript, Test, Tool]
navigation:
- text: 首页
  url: /
- text: 技术
  url: /cn/tech
- text: 笔记
  url: /cn/note
- text: 日志
  url: /cn/blog
- text: 关于我
  url: /cn/about